### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by aluxee** [aluxee/Avitica#45]
Checklist feature is almost done but some edits may be needed:

- [x] ensure there's no duplication of the list and state is as stable as possible
- [x] upon double click of the header, a user can add another item to a checklist and still be able to see all other previous ones
- [x] upon double click of the checklist section, a user can edit a certain item of the checklist
- [x] checklist item upon being checked should be removed from the checklist

**Comment by aluxee** [comment]
checklist feature complete, only need to fix button layouts

- [ ] button adjustment on task and checklist complete
